  active_model_profile: local-qwen

  model_profiles:
    local-qwen:
      provider: anthropic_native
      base_url: http://127.0.0.1:5124
      api_key: "122"
      model: qwen3.5-9b
      temperature: 0.5
      timeout: 120
    gemini-3-flash:
      provider: google_native
      base_url: http://210.45.70.84:30000/
      api_key: "sk-b5685adb3LBGrqpMpzyJpwWrlKQgli1Sg1TLvwxBYUZKkk5c"
      model: gemini-3-flash
      temperature: 0.5
      timeout: 220
    MiniMax-M2.5:
      provider: openai
      base_url: http://210.45.70.84:30000/v1
      api_key: "sk-b5685adb3LBGrqpMpzyJpwWrlKQgli1Sg1TLvwxBYUZKkk5c"
      model: MiniMax-M2.5
      temperature: 0.5
      timeout: 220

  context:
    enabled: true
    max_tokens: 150000
    history_compactor: llm
    recent_turns: 2

  product:
    permission_mode: accept_edits
    enable_codeintel: true
    enable_mcp: true

  ui:
    theme: s4
    show_thinking: true
    right_panel_open: false
